### PR TITLE
Use TypedArray.of(...) instead of new TypedArray([...])

### PR DESCRIPTION
**Pull request by beaufortfrancois**
I find it easier to understand as people might miss the `[...]` when reading. WDYT?
If that looks good to you, I'll update our intro article at https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web as well.

Bonus point: It is shorter!

R: @scheib @g-ortuno

### CODE REVIEW

**Review by scheib — APPROVED** [review]
I could go either way. I think I slightly prefer the previous.

**Comment by g-ortuno** [comment]
No preference here.

**Comment by beaufortfrancois** [comment]
Merging it then ;)

**Comment by beaufortfrancois** [comment]
I'm updating https://github.com/google/WebFundamentals/pull/4139

**Pull request merged**
