### PR TITLE
PaymentRequest samples

### PR DESCRIPTION
**Pull request by rsolomakhin**
This patch adds several samples for PaymentRequest API. Feature
description:

https://www.chromestatus.com/feature/5639348045217792

Latest spec:

https://github.com/w3c/browser-payment-api

### CODE REVIEW

**Comment by sideshowbarker** [comment]
When I run these in Chrome 53.0.2746.0 canary (or Chromium 53.0.2746.0) with `chrome://flags/#enable-experimental-web-platform-features` enabled, I get:

> `Uncaught TypeError: ChromeSamples.status is not a function` 

If I run them in Chrome 52.0.2739.2 dev with `chrome://flags/#enable-experimental-web-platform-features` enabled, when I press the **Run** button, I get `Request cancelled`.

**Comment by rsolomakhin** [comment]
> When I run these in Chrome 53.0.2746.0 canary (or Chromium 53.0.2746.0) with chrome://flags/#enable-experimental-web-platform-features enabled, I get:
> 
> Uncaught TypeError: ChromeSamples.status is not a function

Try to run the samples from such URLs as https://rsolomakhin.github.io/samples/paymentrequest/free-shipping/. If you save the HTML file locally, it will be missing includes. If you clone the repository, be sure to use [Jekyll](https://jekyllrb.com/) to serve it up. Each page is a template, so opening it raw will not be a complete experience. See the [github docs](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/) for more info.

> If I run them in Chrome 52.0.2739.2 dev with chrome://flags/#enable-experimental-web-platform-features enabled, when I press the Run button, I get Request cancelled.

`Request cancelled` usually means that there's no implementation on this platform. Be sure to test on Android. Other platforms are coming in 2017.

**Comment by sideshowbarker** [comment]
> Be sure to test on Android. Other platforms are coming in 2017.

Aha. Well I read the above, I had been trying in desktop canary on OS X.

I suspect that others might also be confused and end up wasting time trying it desktop or other non-Android. Maybe the code should do some platform detection and for non-Android just emit a message on page load saying that it only works on Android.

**Comment by sideshowbarker** [comment]
> Be sure to test on Android. Other platforms are coming in 2017.

Aha. Until I read the above I had been trying to run them in canary on my macbook. Maybe you could add some platform detection to the demo code, to have the demos just emit a message on non-Android platforms saying that the demos will only work on Android.

**Comment by rsolomakhin** [comment]
> Maybe the code should do some platform detection and for non-Android just emit a message on page load saying that it only works on Android.

Done.

I will submit a new pull request here once the first one is merged. [My fork](https://rsolomakhin.github.io/samples/paymentrequest/free-shipping/) is already updated.

**Comment by sideshowbarker** [comment]
> > Maybe the code should do some platform detection and for non-Android just emit a message on page load saying that it only works on Android.
> 
> Done.
> 
> I will submit a new pull request here once the first one is merged. My fork is already updated.

Super—thanks very much!

**Comment by asieke** [comment]
Hey there- wanted to quick ping this thread, can we get @rsolomakhin 's samples merged?

**Comment by jeffposnick** [comment]
👍 Thanks for writing this!

**Pull request merged**
