### PR TITLE
Add Media Capabilities - Decoding Info EME Sample

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR adds sample for "Media Capabilities - Decoding Info EME".

@chcunningham Can you have a look?
Here's a live preview at https://beaufortfrancois.github.io/samples/media-capabilities/decoding-info-eme

Note that the OT token is for googlechrome.github.io, not my live preview domain.

FYI @mounirlamouri

### CODE REVIEW

**Comment by chcunningham** [comment]
LGTM! Thanks a bunch

**Comment by chcunningham** [comment]
One thought. If you like you could add a comment or some hint that, once obtained, they can use the keySystemAccess to setup  the EME playback. Maybe thats clear enough already - I defer to you.

**Comment by beaufortfrancois** [comment]
I've addressed your feedback.

**Comment by beaufortfrancois** [comment]
it is now live at https://googlechrome.github.io/samples/media-capabilities/decoding-info-eme

**Pull request merged**
