### PR TITLE
A minimal App Install Banner demo

### PR DESCRIPTION
**Pull request by PaulKinlan**
This went through a couple of changes as I worked with the eng team to diagnose a critical bug.

This now works.  @addyosmani @jeffposnick would love a review so I can get it in to the post about this feature.

### CODE REVIEW

**Comment by addyosmani** [comment]
Nice work, Paul. Happy to review further. Could you squash your commits please? :) I have a few questions (e.g why we're using `<meta name="viewport" content="width=device-width">` rather than the complete one, but can save till squashed).

**Comment by PaulKinlan** [comment]
How does one squas commits in the Chrome Dev Tools editor and in the github interface?

**Comment by addyosmani** [comment]
Does CDT support git commands? If so, http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by PaulKinlan** [comment]
It does not, I pulled it all in locally on another machine and squashed there instead.  I can't get rid of the merge commit.

**Comment by PaulKinlan** [comment]
Nope. however it was copied from one of the SW examples.  Will sort.

**Comment by addyosmani** [comment]
Reviewed. One other minor comment: we usually include a brief description of the feature https://github.com/GoogleChrome/samples/blob/gh-pages/lexical-declarations-es6/index.html#L49 along with its name (heading) and any other posts or ChromeStatus links (https://www.chromestatus.com/features/4540065577435136) we want to reference at the start of the sample. 

Also mention which version of Chrome and above one can expect this to work in. Could we do this?

**Comment by PaulKinlan** [comment]
Sure I can do this, I mostly copied the formatting and style from another example.  Will add them.

**Comment by addyosmani** [comment]
Thank you :cake:

**Comment by addyosmani** [comment]
One last comment.

**Comment by PaulKinlan** [comment]
Sorted typo

**Comment by addyosmani** [comment]
:+1:

**Pull request merged**
