### PR TITLE
s/Sample/Code Sample/g in few different places

### PR DESCRIPTION
**Pull request by beaufortfrancois**
R: @jeffposnick @marcacohen

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Feel free to close it @PaulKinlan then ;)

**Comment by mco-gh** [comment]
LGTM but happy to defer to @PaulKinlan and @jeffposnick collective preference. Thanks Francois!

**Comment by jeffposnick** [comment]
Counterpoint: Is [CSS](https://googlechrome.github.io/samples/image-rendering-pixelated/index.html) "code"? Is an [HTTP header](https://googlechrome.github.io/samples/csp-upgrade-insecure-requests/index.html) "code"? We've put together samples for both, and I don't think it's meaningful to change the repo's README to refer to "code" samples.

**Comment by addyosmani** [comment]
I agree with Jeff in that I don't think it adds value to apply changes to refer to "code samples" vs just "samples" in this particular case.

**Comment by beaufortfrancois** [comment]
Let's close it then ;)

**Comment by mco-gh** [comment]
As the instigator of this idea, I'm fine with dropping this PR. Sorry for wasting your time Francois but thanks for considering it.

**Pull request closed without merging**
