### PR TITLE
IDB getAll() sample

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @addyosmani @gauntface @beaufortfrancois 
CC: @inexorabletash

This implements a basic sample to go along with the new M48 IndexedDB "batch get" methods (https://www.chromestatus.com/feature/6537756637396992).

I'm using a light Promise wrapper around getting the IndexedDB instance, but I don't think that's too distracting.

You can view a deployed version of this sample at https://jeffy.info/samples/idb-getall/

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
To be honest, I was confused about the Promise wrapper. I think something simpler as below would help developers to focus more on the `getAll` method.

``` diff
-var DB_NAME = 'timestamps';
-var DB_VERSION = 1;
 var STORE_NAME = 'store';
-var dbInstance;
-
-// Simple Promise-based wrapper around getting an IndexedDB instance.
-function getDB() {
-  if (dbInstance) {
-    return Promise.resolve(dbInstance);
-  }
-
-  return new Promise(function(resolve) {
-    var request = indexedDB.open(DB_NAME, DB_VERSION);
-
-    request.onupgradeneeded = function() {
-      request.result.createObjectStore(STORE_NAME, {autoIncrement: true});
-    };
-
-    request.onsuccess = function() {
-      dbInstance = request.result;
-      resolve(dbInstance);
-    };
-  });
-}
+var db;

+var request = indexedDB.open('timestamps', 1);
+request.onsuccess = function() {
+  db = request.result;
+};
+request.onupgradeneeded = function() {
+  db.createObjectStore(STORE_NAME, { autoIncrement: true});
+};

 document.querySelector('#add').addEventListener('click', function(event) {
-  getDB().then(function(db) {
   var transaction = db.transaction(STORE_NAME, 'readwrite');
   var objectStore = transaction.objectStore(STORE_NAME);
   objectStore.put(Date.now());
-  }).catch(function(error) {
-    ChromeSamples.setStatus(error);
-  });
 });

 document.querySelector('#display').addEventListener('click', function(event) {
-  getDB().then(function(db) {
   var transaction = db.transaction(STORE_NAME, 'readonly');
   var objectStore = transaction.objectStore(STORE_NAME);
   // IDBObjectStore.getAll() will return the full set of items in our store.
   objectStore.getAll().onsuccess = function(event) {
     var timestamps = event.target.result;
-      ChromeSamples.setStatus('There are ' + timestamps.length + ' timestamps saved in IndexedDB: '
-        + timestamps.join(', '));
+    ChromeSamples.setStatus('There are ' + timestamps.length +
+        ' timestamps saved in IndexedDB: ' + timestamps.join(', '));
   };
-  }).catch(function(error) {
-    ChromeSamples.setStatus(error);
-  });
 });
```

**Comment by jeffposnick** [comment]
It looks like there's a race condition in your proposed modifications, in that the `click` event listeners might be triggered before `db` is assigned to a fully functional IndexedDB instance.

The promise wrapper could be overkill, sure. What I could do is start out with the buttons initially disabled, and only enable them inside of `request.onupgradeneeded`, which should be safe enough for a sample.

**Comment by beaufortfrancois** [comment]
Yeah you're right. 
Enabling buttons should be enough then.

**Comment by jeffposnick** [comment]
PTAL.

**Comment by beaufortfrancois** [comment]
LGTM except nit.

**Comment by gauntface** [comment]
Worth adding a check when the sample is run on a browser that doesn't support this API?

**Comment by jeffposnick** [comment]
@gauntface, there's a global [`error` handler](https://github.com/GoogleChrome/samples/blob/gh-pages/_layouts/default.html#L42) in place to avoid having to add in feature checks in all the samples. Here's what it should look like on unsupported browsers:

image

(The earlier version of this samples didn't trigger the handler, since a failure involved a promise rejection rather than an exception, but the modified version without promises will trigger it.)

**Comment by gauntface** [comment]
My main thinking is that there may be developers that want to feature detect.

**Comment by jeffposnick** [comment]
Given that there's a clear fallback behavior to use, sure, I'll update the sample to use that if `getAll()` isn't supported.

**Comment by jeffposnick** [comment]
@gauntface PTAL. I've modified the sample to check for `getAll()` support, and fallback to cursors if it's not supported.

**Comment by gauntface** [comment]
LGTM

**Pull request merged**
