### PR TITLE
Add two-token web session management demo app.

### PR DESCRIPTION
**Pull request by kongguibin**
Add an example Google App Engine app, which leverages service worker to support two-token based web session management.

### CODE REVIEW

**Comment by jeffposnick** [comment]
Hello @kongguibin—I'm not sure that this repo is the best home for this kind of sample, given its dependencies on Java App Engine. It's intended purpose is to house samples closely tied to new functionality added to each version of Chrome (tracked at https://www.chromestatus.com/features) that can be demonstrated as part of a static hosted page served from the `gh-pages` branch.

Would you be open to going through the normal Google open source releasing process and creating a new repo for this?

**Comment by kongguibin** [comment]
I changed my primary email address to my google.com one. Hope the CLA is not an issue any more.

**Comment by kongguibin** [comment]
@owencm Owen, can you explain why we select this repository?

**Comment by PaulKinlan** [comment]
I think we should make a new repo, it can be done easily. This is about a
process/method so I think it can standalone.

**Comment by owencm** [comment]
I've started a thread with all of you and Taylor to discuss if this is the right place for this to live. Lets discuss there.

**Comment by jeffposnick** [comment]
Closing, as this has moved to https://github.com/GoogleChrome/two-token-sw

**Pull request closed without merging**
