### PR TITLE
Add page icon_url option

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Hello Jeff,

This simple patch adds an option to define a URL for the icon that will be used for the favicon and next to the title. Let me know what you think of it.

R=@jeffposnick

screenshot 2016-04-22 at 11 39 16 am

### CODE REVIEW

**Comment by jeffposnick** [comment]
Hey @beaufortfrancois—apparently there's a recently introduced linting violation that is making Travis CI unhappy. It's not directly related to this PR, but it is in the Bluetooth code. Would you mind fixing it and updating so that we can merge while green?

```
/home/travis/build/GoogleChrome/samples/web-bluetooth/device-disconnect.js
  17:41  error  Missing semicolon  semi
✖ 1 problem (1 error, 0 warnings)
```

**Comment by beaufortfrancois** [comment]
Thanks for warning me @jeffposnick!
I've fixed linting error in https://github.com/GoogleChrome/samples/commit/104df49796aa5d67b38eaea2335e954c38c9196d.

**Comment by jeffposnick** [comment]
👍

**Comment by beaufortfrancois** [comment]
Yeah!

**Pull request merged**
