### PR TITLE
Fix payment-request demos w/ regards to new specs

### PR DESCRIPTION
**Pull request by jonathanGB**
Current state of **PaymentRequest** demos had two problems related to the ongoing specs:

1. Use of `supportedMethods` is now a *String* rather than an *Array*
2. Re-using the same **PaymentRequest** instance when clicking on "Buy" would lead to errors (at least on FF). I have not delved too much into the causes, but my intuitition is that showing a previous **PaymentRequest** causes an error (as it wasn't part of "user activation")
image
image

Fix to **1** was trivial. 
Fix to **2** required to create a new **PaymentRequest** instance every time we wanted to show the interface. 

With the current PR, the demos now work well with the new specs.

Note: this can replace PR #534.

CC: @rsolomakhin @mnoorenberghe

### CODE REVIEW

**Comment by jonathanGB** [comment]
I signed it!

**Comment by mnoorenberghe** [comment]
> Fix to 2 required to create a new PaymentRequest instance every time we wanted to show the interface.

I suspect that is just a Fx bug and probably shouldn't be in this PR.

**Comment by mnoorenberghe** [comment]
@jonathanGB Do you have time to revert the changes for part 2?

**Comment by jonathanGB** [comment]
I'm gonna look at it this week!

**Comment by jonathanGB** [comment]
@mnoorenberghe this should do it; only "supportedMethods" has been changed now.

**Review by mnoorenberghe — COMMENTED** [review]
LGTM. Maybe @beaufortfrancois can review while @rsolomakhin is away?

**Review by rsolomakhin — APPROVED** [review]

**Comment by rsolomakhin** [comment]
@agektmr Please merge.

**Review by PaulKinlan — APPROVED** [review]

**Pull request merged**
