### PR TITLE
Add label to images to clarify which is currently displayed

### LINKED ISSUE #625: webp picture element sample not working
Wondering why I cant get webp support on my own homepage to work I came across your sample at https://googlechrome.github.io/samples/picture-element/, specifically the second example (the one with the butterfly).

Alas, opening it with Chrome (70) only shows on jpg img, not the webp one which is specified with '<source type="image/webp">'

### PR DESCRIPTION
**Pull request by rejas**
Fixes https://github.com/GoogleChrome/samples/issues/625 
Or rather clarifies it by showing if it is the jpg or webp image currently displayed

### CODE REVIEW

**Comment by rejas** [comment]
I signed it!

**Comment by rejas** [comment]
Hi @beaufortfrancois are you the correct person to ping? Would like to know if I can do anything to get this merged?

**Comment by rejas** [comment]
Hey @googlebot who should I ping to get this merged?

**Comment by rejas** [comment]
pinging @beaufortfrancois to know if I can do something here to get it merged?

**Comment by beaufortfrancois** [comment]
Sorry for missing this one! Thank you @rejas !

**Comment by rejas** [comment]
No worries, thx for merging. Have a nice day!

**Pull request merged**
