### PR TITLE
Add MediaStream Image Capture API Sample

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Hello @samdutton,

Can you review this sample?
I've tried to keep it very simple, and not showcase yet `PhotoCapabilities`. WDYT?

You can give it a try at https://beaufortfrancois.github.io/samples/image-capture/

screenshot 2016-11-22 at 11 31 53 am

### CODE REVIEW

**Comment by samdutton** [comment]
LGTM.

I have a couple of suggestions, but feel free to ignore them :).

> I've tried to keep it very simple, and not showcase yet PhotoCapabilities. WDYT?

It adds a bit of complexity, but it might be nice to add zoom, even if this part of the API changes (see the example at [simpl.info/ic](https://simpl.info/ic)).

**Comment by beaufortfrancois** [comment]
I was thinking if we may want another sample dedicated to `zoom`. WDYT?

**Comment by samdutton** [comment]
Good point — maybe another sample focused (ha ha) on camera capabilities.

**Comment by beaufortfrancois** [comment]
I'll do that today then.

**Comment by beaufortfrancois** [comment]
OK. So we have now two samples you can try at 
https://beaufortfrancois.github.io/samples/image-capture/grab-frame-take-photo.html
https://beaufortfrancois.github.io/samples/image-capture/update-camera-zoom.html (This one works better with Android camera from)

**Comment by samdutton** [comment]
Ah — excellent. Thanks! I'll take a look.

**Comment by beaufortfrancois** [comment]
@samdutton (gentle ping)

**Comment by samdutton** [comment]
Zoom demo looks great — LGTM.

Did a PR (nit) for the first demo:

a ImageBitmap => an ImageBitmap


Also — I'd also be inclined to change 'photographic device such as a
webcam' to 'camera', since the difference between photo and video is
meaningful here — and 'webcam' sounds specifically like something for a
desktop machine (i.e. not a mobile device camera).

**Comment by beaufortfrancois** [comment]
@samdutton Thank you! It should be addressed in https://github.com/GoogleChrome/samples/pull/449/commits/1be1c99a9c3dc05c24347f03d084618fe01b8c48

**Comment by PaulKinlan** [comment]
@beaufortfrancois @samdutton - can we land this asap.

**Comment by samdutton** [comment]
This is ready to go as far as I'm concerned.

**Comment by beaufortfrancois** [comment]
Let's merge!

**Pull request merged**
