### PR TITLE
Update React Perf Example

### PR DESCRIPTION
**Pull request by mrblueblue**
I've corrected the `lastUpdate` property from `this.props.image` from the incorrect key of `lastUpdated`

I've also corrected the use of the `moment` api. Since `this.props.image.lastUpdate` is epoch time, you have to invoke `moment.unix()` on it.

Lastly, I've updated React to version 0.14.2.

### CODE REVIEW

**Comment by mrblueblue** [comment]
`I signed it`

**Comment by jeffposnick** [comment]
CC: @paullewis

**Comment by paullewis** [comment]
Wondering if this sample needs to exist anymore. It's served it's purpose imo. @addyosmani @PaulKinlan wdyt?

**Comment by paullewis** [comment]
Sorry @mrblueblue, should've said thank you for the PR first. I'm just debating whether or not this really fits in the repo.

**Comment by addyosmani** [comment]
Did you want to move it elsewhere for future reference? If not, we could probably nix it.

**Comment by paullewis** [comment]
Just nix it; there's a copy on my GitHub fork (which is what's linked on the post)

**Pull request closed without merging**
