### PR TITLE
Improve comment precision in File constructor sample

### PR DESCRIPTION
**Pull request by pwnall**

### CODE REVIEW

**Comment by jeffposnick** [comment]
Thanks for the contribution, and sorry for the delay. One small step before I can merge—I'd need you to read through and electronically submit the Google Contributor Licensing Agreement, available at https://cla.developers.google.com/about/google-individual

Please ping this PR if/when you've done so. Thanks!

**Comment by pwnall** [comment]
Hi, @jeffposnick!

I signed the CLA some time ago. I'm the Chromium committer that implemented the File constructor. :heart: 

Look for `Victor Costan` here.
https://chromium.googlesource.com/chromium/src.git/+/master/AUTHORS

**Comment by jeffposnick** [comment]
Awesome! Thanks for confirming.

**Comment by pwnall** [comment]
Thank you for merging! :+1:

**Pull request merged**
