### PR TITLE
Move Android Pay sample to Google Pay

### PR DESCRIPTION
**Pull request by madmath**
Changes:
* The payment method name changed from https://android.com/pay to https://google.com/pay
* Various comment changes

### CODE REVIEW

**Comment by madmath** [comment]
I signed it!

**Comment by madmath** [comment]
cc @agektmr

**Comment by madmath** [comment]
cc @rsolomakhin

**Review by rsolomakhin — APPROVED** [review]
@agektmr Please merge.

**Review by rsolomakhin — APPROVED** [review]
@agektmr Please merge

**Review by PaulKinlan — APPROVED** [review]

**Pull request merged**
