### PR TITLE
Add Web Bluetooth Availability Sample

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR is adding two samples for [Web Bluetooth getAvailability()](https://www.chromestatus.com/features/6229592081694720)

Does that look good @odejesush?

Live preview:
https://beaufortfrancois.github.io/samples/web-bluetooth/availability.html
https://beaufortfrancois.github.io/samples/web-bluetooth/availability-async-await.html
https://beaufortfrancois.github.io/samples/web-bluetooth/index.html

FYI @jyasskin @g-ortuno @scheib

### CODE REVIEW

**Comment by odejesush** [comment]
Yup LGTM, thanks for adding these.

I still need to implement the `availabilitychanged` event though.

**Comment by beaufortfrancois** [comment]
I'll wait for `availabilitychanged` to be implemented before merging those.
Then, I'll add these samples to https://www.chromestatus.com/feature/6229592081694720

**Comment by beaufortfrancois** [comment]
@odejesush I've updated those samples to be in M78 and added checks for "onavailabilitychanged" so that it works in Chrome 79.

**Comment by beaufortfrancois** [comment]
I've added those samples to https://www.chromestatus.com/feature/6229592081694720.
They are live:
- https://googlechrome.github.io/samples/web-bluetooth/availability-async-await.html
- https://googlechrome.github.io/samples/web-bluetooth/availability.html

**Pull request merged**
