### PR TITLE
Add MediaError.message sample

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Hello @wolenetz,
May you review this s{i,a}mple for MediaError.message?

Source: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/yDIyWozG1xk

screenshot 2017-05-22 at 3 45 17 pm

### CODE REVIEW

**Comment by wolenetz** [comment]
This quick sample LGTM. Perhaps a small note that this sample demonstrates only a tiny fraction of such messages.

**Comment by beaufortfrancois** [comment]
Thank you @wolenetz! I've addressed your feedback.

**Comment by beaufortfrancois** [comment]
Here it is live: https://googlechrome.github.io/samples/media/error-message.html

**Comment by beaufortfrancois** [comment]
FYI @mounirlamouri

**Pull request merged**
