### PR TITLE
[WebTransport] Add the protocol version to response

### PR DESCRIPTION
**Pull request by yutakahirano**
...to be aligned with
https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-02.

### CODE REVIEW

**Comment by yutakahirano** [comment]
@jeffposnick @bashi PTAL

**Review by bashi — APPROVED** [review]

**Comment by jeffposnick** [comment]
Thanks!

**Comment by aboba** [comment]
The problem seems to have re-emerged in Canary M98.0.4696.0. 

This can be reproduced on:
https://webrtc.internaut.com/wt2/ which is running the python server.  

It runs on Chrome M95, but not on Canary M98.

**Comment by bashi** [comment]
Thank you for the report. Yeah we also noticed that WPTs started failing recently. We are investigating the cause. https://bugs.chromium.org/p/chromium/issues/detail?id=1268607

**Pull request merged**
