### PR TITLE
Add indexed_db_observers sample

### PR DESCRIPTION
**Pull request by dmurph**
Now that values and transactions are supported in IDB Observers, I'm comfortable releasing this sample. I may iterate a bit later to show off transaction support.

@jeffposnick for this update.

### CODE REVIEW

**Comment by jeffposnick** [comment]
👍 from my perspective.

CC: @petele @PaulKinlan so that this is on their radar, too.

**Comment by beaufortfrancois** [comment]
@dmurph I've tweaked your PR at https://github.com/GoogleChrome/samples/pull/475. WDYT?

**Comment by dmurph** [comment]
That seems fine.

**Comment by beaufortfrancois** [comment]
Closing with https://github.com/GoogleChrome/samples/pull/475 and https://github.com/GoogleChrome/samples/pull/479

**Pull request closed without merging**
