### PR TITLE
WebRTC VP8 v VP9 demo

### PR DESCRIPTION
**Pull request by samdutton**
As discussed with @PaulKinlan. 

This is a copy of go/vp8vsvp9 for the forthcoming Web Fundamentals update: _VP9 is now available in WebRTC_.

Can be viewed at [samdutton.github.io/samples/webrtc-vp8-vp9](http://samdutton.github.io/samples/webrtc-vp8-vp9/).

### CODE REVIEW

**Comment by jeffposnick** [comment]
Thanks, @samdutton!

There are a number of linting errors, revealed by the [Travis CI build](https://travis-ci.org/GoogleChrome/samples/builds/106333561). You can also run linting locally via `npm run lint`.

Many of them come from third-party code, which I'm fine with just ignoring. You can add `webrtc-vp8-vp9/js/third_party/` to the existing [`.eslintignore` file](https://github.com/GoogleChrome/samples/blob/gh-pages/.eslintignore).

The rest of them are from first-party code that's getting checked in, and it would be ideal to resolve those. Switching from `"` to `'` and adding a `/* eslint-env browser, jquery */` comment to the top of the files using jQuery should take care of a lot of them.

**Comment by samdutton** [comment]
Thanks — will fix.

**Comment by samdutton** [comment]
I've linted (and removed a code/files that weren't being used).

**Also — I'd prefer for this not be merged for the moment. I'm double checking that it's definitely OK to go live. I'll confirm as soon as I get the go ahead.**

**Comment by jeffposnick** [comment]
Sure thing. Will hold off on a deeper review of the code until we know the outcome.

**Comment by jeffposnick** [comment]
I'm testing out the code now (in Chrome 50 Canary), and running into some bugs in which the videos don't load reliably when using the "Pick a Video" interface. It's not too hard to get into the state where one or both aren't visible:

image

image

There aren't any JS Console errors when this happens. Do you have any idea what's going on, @samdutton?

**Comment by samdutton** [comment]
Thanks Jeff — I'll take a look.

**Comment by jeffposnick** [comment]
Hey @samdutton—any ideas as to what was causing the video loading failures? This is a valuable demo, but we obviously don't want to merge until the reliability is there.

**Comment by samdutton** [comment]
Hi Jeff — I've actually been working on a simpler version of this. Been
somewhat snowed under, but I'll upload when it's ready.

**Comment by jeffposnick** [comment]
Sounds good. Would you like to close this PR if we're talking about a substantial rewrite?

**Comment by samdutton** [comment]
Sure — that probably makes sense.

**Pull request closed without merging**
