### PR TITLE
Subresource integrity example

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @addyosmani @ebidel @gauntface @PaulKinlan etc.
CC: @mikewest 

Quick sample showing off the use of subresource integrity to allow one CSS file to load and block another.

### CODE REVIEW

**Comment by addyosmani** [comment]
Sample reviewed and LGTM. @mikewest would be great to get your sign-off before we land this.

**Comment by addyosmani** [comment]
friendly ping @mikewest as we'll need to land this before Thursday for M45 posts going out :)

**Comment by ebidel** [comment]
Lgtm

**Comment by mikewest** [comment]
LGTM too, sorry for the delay!

**Comment by jeffposnick** [comment]
Thanks for the review, all!

**Pull request merged**
