### PR TITLE
Added more background for array includes ES7 sample

### PR DESCRIPTION
**Pull request by beaufortfrancois**
As suggested by @addyosmani few weeks ago at (https://github.com/beaufortfrancois/samples/commit/f8535ed0c34b998270468ca5a48ef31a993598f5#commitcomment-12996896).

### CODE REVIEW

**Comment by jeffposnick** [comment]
The change seems :+1:, but I'm investigating the Travis CI build failure and would like to figure out what's up with that prior to merging.

**Comment by addyosmani** [comment]
Changes here LGTM. Waiting on CI resolution :+1:

**Comment by jeffposnick** [comment]
Looking at the Travis CI logs, previous successful builds have been using the `jekyll` 2.4.0 gem, and the current failing build is using `jekyll` 1.5.1. Digging in a bit more as to what is causing that downgrade—it's presumably not anything related to this PR, but I don't want to merge and kick off a GitHub Jekyll build before I understand what the problem is and whether it might also affect GitHub Pages.

**Comment by addyosmani** [comment]
SGTM. We're not in a release crunch atm so I think it's fine to hold off until you're comfortable the build situation is a little more clear.

**Comment by jeffposnick** [comment]
https://github.com/GoogleChrome/samples/pull/215 should resolve it—I broke it out into a separate PR for a cleaner review.

**Comment by jeffposnick** [comment]
@beaufortfrancois, can you rebase/merge your branch with this repo's `gh-pages` and update this PR to confirm that the CI check now passes?

**Comment by beaufortfrancois** [comment]
I will

**Comment by beaufortfrancois** [comment]
Done.

**Comment by jeffposnick** [comment]
Thanks!

**Pull request merged**
