### PR TITLE
Fix typo: "DevTool's" -> "DevTools"

### PR DESCRIPTION
**Pull request by lgarron**
[DevTools](https://developer.chrome.com/devtools) is the official (abbreviated) name.

### CODE REVIEW

**Comment by lgarron** [comment]
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project, in which case you'll need to sign a Contributor License Agreement (CLA).

Do I seriously need to sign in using my personal Google account and tie it to my code email account in order to do this? :-/

**Comment by addyosmani** [comment]
Unfortunately, yes :/ Sorry about that! The CLA process requires us to ask this even for super small changes. Apologies for the process.

**Comment by flopdraal** [comment]
> Unfortunately, yes :/ Sorry about that! The CLA process requires us to ask this even for super small changes. Apologies for the process.

Do you realize that this process of contributions is terribly annoying for every not Googler? Everybody is trying to make a lower barrier to entry while this is literally requiring 5 minutes of work to remove a single quote.

**Comment by lgarron** [comment]
> not Googler

And Googler! (I'm even in https://github.com/google.)
I don't mind signing a CLA using my code email, I just refuse to do whatever thing requires me to tie it to my Google account for this.

**Pull request closed without merging**
