### PR TITLE
KeyboardEvent.code attribute sample

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @addyosmani @gauntface @beaufortfrancois 

Sample code for https://www.chromestatus.com/feature/5228092293382144

Live version available for preview at https://jeffy.info/samples/keyboardevent-code-attribute/

### CODE REVIEW

**Comment by addyosmani** [comment]
PR LGTM.

**Comment by beaufortfrancois** [comment]
I wonder if we should call `event.preventDefault();` as well so that user can fully interact with the sample without to worry about typing weird keys combos.

**Comment by jeffposnick** [comment]
It didn't seem necessary when I was playing around with the demo.

Ultimately this new attribute is focused on individual keypresses rather than modifier keys. If someone wants to type Control/Apple+W, I'd rather it closed the tab like it would by default rather than hijacking things.

**Comment by beaufortfrancois** [comment]
OK.

**Pull request merged**
