### PR TITLE
Update Instructions to Match Console.

### PR DESCRIPTION
**Pull request by jpmedley**
@jeffposnick 

Just got around to trying push with the new laptop. I got it to work. The change below is based on what I had to do. Ping me if you have any questions.

Joe

### CODE REVIEW

**Comment by jeffposnick** [comment]
I've always seen this use a 'Server' key before, and haven't had any specific problems using that.

Anyway, this is @gauntface's demo and he's probably more in the know about the current state of GCM requirements.

**Comment by jpmedley** [comment]
Reed the comments to the first answer here.

http://stackoverflow.com/questions/11307689/when-sending-messages-using-gcm-i-keep-getting-the-response-mismatchsenderid

It seems to vary for some reason I can't pin down.

Joe Medley | Technical Writer, DevPlat | jmedley@google.com | 816-678-7195

**Comment by jpmedley** [comment]
Sam's article also has Browser Key.

https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-04?hl=en#get-credentials

**Comment by addyosmani** [comment]
Friendly ping @gauntface

**Comment by gauntface** [comment]
Just tried and can only get this working with server key.

**Comment by beaufortfrancois** [comment]
@jpmedley @gauntface Console strings have been updated as you can see.
Shall we reflect these in the sample?

screenshot 2016-08-24 at 8 37 24 am

**Comment by beaufortfrancois** [comment]
(gentle ping)

**Comment by addyosmani** [comment]
Imo we should reflect them in the sample.

**Comment by jeffposnick** [comment]
Closing this as it's been superseded by #425

**Pull request closed without merging**
