### PR TITLE
jshint-based linting

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @addyosmani @PaulKinlan @gauntface _et alii_

This introduces a new `linter.rb` script, which can be run either manually or via `.git/hook/pre-commit` (recommended), and checks for the following:
- a successful Jekyll site build
- for each (committed) file, that all boilerplate content has been removed
- for each (committed) file, that the templated version of it under _site/ passes `jshint`

The idea is that for now this would be recommended for all new/modified files, and we'd also clean up the backlog/adjust `.jshintrc` to make `jshint` happy with everything. At that point, we can update Travis CI to automatically lint the full site as part of every PR.

Related to https://github.com/GoogleChrome/samples/issues/141, but not enough to close it out yet.

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Some minor comments:
- Should we not use a [rake](https://github.com/ruby/rake) file and have a task for test/build that includes the linter.
- It feels rather than a commit hook we can get travis to build and test all PR's and reject them if they break the build.

**Comment by jeffposnick** [comment]
Using [`rake`](https://github.com/ruby/rake) makes sense. I'll refactor this PR to do that.

Regarding the Travis CI integration, my thinking is that we should get all the pre-existing samples cleaned up first (which will need to be done in future PRs), and once we get to a "clean" baseline, start linting the entire generated site as part of the Travis CI checks. I don't know of a clean way to tell Travis CI to just check a subset of changed files rather than the whole generated site, while that's possible to do via a `pre-commit` hook.

**Comment by addyosmani** [comment]
> Regarding the Travis CI integration, my thinking is that we should get all the pre-existing samples cleaned up first (which will need to be done in future PRs), and once we get to a "clean" baseline, start linting the entire generated site as part of the Travis CI checks. 

This sgtm.

**Comment by jeffposnick** [comment]
PTAL for this stage in the continuing process of implementing continuous integration/linting.

I've addressed some of the comments, but stopped short of wrapping up everything in a `Rakefile` at this point. When I tried that approach, the `.git/hook/pre-commit` setup ended up being more complicated—it would need to be a wrapper shell script which in turn invoked `rake` which in turn executed the existing Ruby code.

In a follow-up PR that adds linting to the Travis CI build process I may wrap things up in a `Rakefile`, but I want to approach this in smaller steps.

**Comment by gauntface** [comment]
I struggled with this tbh.

Having to run this on pre-commit only is frustrating when I'd rather know while I'm working on the code. When there is an issue in the pre-commit step it simply states there was an issue, not what the issue was or where it resides.

I ended up creating a gulptask that just watches for changes and runs everything through JSHint. This had its own issues in that it doesn't like the yaml at the top of the files using jekyll templates. To overcome this I had to jekyll serve, point gulp at the _site directory and then basically find the errors in the final html page, then match that back to the source and fix it there, presumably this would be the same for the pre-commit hook?

When it came to actually commiting the final code, the pre-commit hook just output:

```
.git/hooks/pre-commit:34:in ``': No such file or directory - bundle (Errno::ENOENT)
    from .git/hooks/pre-commit:34:in `<main>'
```

It had worked prior to this outputting:

```
.git/hooks/pre-commit:68:in `<main>': One or more errors were found. (RuntimeError)
```

Was there a reason these wasn't just moved to a build process where it could be used during development?

I have zero confidence if everything is fix, but I had a crack here: https://github.com/gauntface/samples

Happy to make a PR, but it's not validated again the linter.rb file so have held off for now.

**Comment by jeffposnick** [comment]
I'm happy to defer to your approach, @gauntface.

https://www.npmjs.com/package/eslint-plugin-html might allow us to use `eslint` instead of `jshint`, which would be really nice.

**Pull request merged**
