### PR TITLE
Adds read-write decorator

### PR DESCRIPTION
**Pull request by paullewis**
PTAL @PaulKinlan

### CODE REVIEW

**Comment by paullewis** [comment]
I signed it!

**Comment by paullewis** [comment]
:runner::dash:

**Comment by PaulKinlan** [comment]
It might sound stupid, but I feel like the folder name should be decorators-es7 there are a bunch of *-es6 ones.

**Comment by paullewis** [comment]
(We should rename generators as well)

**Comment by PaulKinlan** [comment]
sounds like a plan.

**Comment by addyosmani** [comment]
Ignore me, but I'm going to leave a gripe here.

Was this code reviewed by someone familiar with decorators or ES6? :/ For every other ES6 or ES7 feature we've been landing, we've been making sure to get the actual source reviewed. Looping in V8 eng privately or someone in the community familiar with the feature. This place otherwise becomes a dumping ground for yolo experiments. It's supposed to be authoritative. 

The same could be said for https://github.com/GoogleChrome/samples/pull/138. We're landing code here and assuming it's 100% perfect. I'm exciting by EVERYTHING @paullewis has been working on and want to see it ship fast, but we're introducing a change in the way we've been tackling ES6/7 code additions here lately. If it's intentional, it means we're fine with landing non-reviewed code for any sample. If not, we should be mindful of reviews being sought out.

**Comment by paullewis** [comment]
@addyosmani I didn't merge the PR myself for the _precise_ reason that I wanted it reviewed. It was reviewed by @PaulKinlan. If there's an additional stipulation that it needs to be double-checked by someone else, then that's new info to me. With regards to #138, that was a temporary move to allow people to inspect the perf test, with the ultimate aim of shifting it to a dedicated perf repo.

**Pull request merged**
