### PR TITLE
Fixing changes from the permission API

### PR DESCRIPTION
**Pull request by gauntface**
There has been a change in the permissions spec to use state rather status - this PR just adds this in.

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
LGTM

**Comment by beaufortfrancois** [comment]
@mounirlamouri will appreciate ;)

**Comment by beaufortfrancois** [comment]
@gauntface We may want to update https://developers.google.com/web/updates/2015/04/permissions-api-for-the-web as well.

**Comment by gauntface** [comment]
Seperate PR is in flight for that :)

**Pull request merged**
