### PR TITLE
Added Block modal dialogs in a sandboxed iframe Sample

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Hello @mikewest,

Can you review this sample for modal dialogs blocked in a sandboxed frame?
If you don't want to run the sample, here's a quick look at it:

screenshot 2015-07-28 at 12 12 05 pm

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
cc @jeffposnick for reviewing general look.

**Comment by mikewest** [comment]
The code LGTM, thanks for putting this together! Will you do something
similar for "allow-popups-to-escape-sandbox"?

**Comment by beaufortfrancois** [comment]
I will ;)

**Comment by jeffposnick** [comment]
The comments from https://github.com/GoogleChrome/samples/pull/191 apply here as well.

**Comment by beaufortfrancois** [comment]
Thank you @jeffposnick for this valuable feedback. I didn't realize html_snippet was actually meant for that. I've addressed all your feedback there.

**Comment by beaufortfrancois** [comment]
That makes the sample much better. See below
screenshot 2015-07-31 at 11 08 06 am

**Pull request merged**
