### PR TITLE
Add es6 extended object literals sample

### PR DESCRIPTION
**Pull request by surma**
I hope I hit the tone of the samples.

@addyosmani Please review

### CODE REVIEW

**Comment by surma** [comment]
@addyosmani Please review, again ;) I tried to make it less contrived (thanks for the link).

I also remove the invocation of the generator. It felt like it added to much noise and iterator/generator usage is covered in a separate sample.

**Comment by surma** [comment]
Sounds good to me. Done

**Comment by surma** [comment]
That’s what happens when you just copy-and-paste from an older commit :-/ Fix’d.

**Comment by addyosmani** [comment]
:+1:

**Pull request merged**
